### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by JoshuaAndrewN** [Auctionator/DragonflightHelper#10]
8x ...dOns/DragonflightHelper/core/configuration/theme.lua:104: attempt to index field 'sections' (a nil value)
[string "@DragonflightHelper/core/configuration/theme.lua"]:104: in function `upgrade_config'
[string "@DragonflightHelper/core/configuration/theme.lua"]:47: in function `notify'
[string "@DragonflightHelper/core/events/manager.lua"]:45: in function `handle'
[string "@DragonflightHelper/core/events/manager.lua"]:15: in function <...ceDragonflightHelper/core/events/manager.lua:15>

Locals:
self = <table> {
 get_sections = <function> defined @DragonflightHelper/core/configuration/theme.lua:184
 upgrade_config = <function> defined @DragonflightHelper/core/configuration/theme.lua:97
 init = <function> defined @DragonflightHelper/core/configuration/theme.lua:12
 config = <table> {
 }
 notify = <function> defined @DragonflightHelper/core/configuration/theme.lua:35
 to_message = <function> defined @DragonflightHelper/core/configuration/theme.lua:141
 get_is_showing = <function> defined @DragonflightHelper/core/configuration/theme.lua:168
 get_background_opacity = <function> defined @DragonflightHelper/core/configuration/theme.lua:164
 get_font = <function> defined @DragonflightHelper/core/configuration/theme.lua:152
 get_completed_quest_color = <function> defined @DragonflightHelper/core/configuration/theme.lua:202
 get_statusbar = <function> defined @DragonflightHelper/core/configuration/theme.lua:160
 get_section = <function> defined @DragonflightHelper/core/configuration/theme.lua:192
 get_is_locked = <function> defined @DragonflightHelper/core/configuration/theme.lua:176
 get_accepted_quest_color = <function> defined @DragonflightHelper/core/configuration/theme.lua:210
 get_incomplete_quest_color = <function> defined @DragonflightHelper/core/configuration/theme.lua:206
}
(*temporary) = nil
(*temporary) = "Profession One"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'sections' (a nil value)"
SECTIONS = <table> {
 TIMERS = "Timers"
 FACTIONS = "Factions"
 TODOS = "Todos"
 PROFESSIONS_TWO = "Profession Two"
 PROFESSIONS_ONE = "Profession One"
 FRIENDS = "Friends"
}
SKILL_SUBSECTIONS = <table> {
 MobDrops = "MobDrops"
 Trainer = "Trainer"
 Gathering = "Gathering"
 ProfessionMaster = "ProfessionMaster"
 Treatise = "Treatise"
 WorldDrops = "WorldDrops"
 Weekly = "Weekly"
 Azley = "Azley"
}

**Comment by jrobcodes** [comment]
@JoshuaAndrewN 
1. Does this happen on every login, or has it stopped?
2. If it does happen, can you delete your saved variables file, and see if it happens again?

**Comment by JoshuaAndrewN** [comment]
Funny thing is it doesn't happen with every character.  I'll delete my saved variables file and see if that corrects it though.

**Comment by JoshuaAndrewN** [comment]
After deleting my saved variables, a character that was getting the error yesterday isn't today.  I think that fixed it.  Thank you!
