### ISSUE TITLE
[Feature Request] Font & Texture Customization

### ISSUE THREAD

**Issue by MichelPate** [Auctionator/DragonflightHelper#2]
**Is your feature request related to a problem? Please describe.**
I'd like to request a new feature that allows users to customize the font and texture for the status bar and titles.

**Describe the solution you'd like**
I suggest implementing an option to change the font and texture for the status bar and titles using the _LibSharedMedia-3.0_ library. This would make the customization more universal and allow users to better match the addon's appearance with their other UI elements.

**Describe alternatives you've considered**
An alternative solution could be providing a built-in selection of fonts and textures, but using the _LibSharedMedia-3.0_ library would make it easier to maintain compatibility with a wider range of user preferences and addons.

**Comment by jrobcodes** [comment]
In progress; need to work out a few bugs, but its getting close:

<img width="352" alt="Monosnap World of Warcraft 2023-04-17 00-27-57" src="https://user-images.githubusercontent.com/838110/232414879-b1a84840-eb2a-4aea-9f51-be4c25493c4c.png">

**Comment by jrobcodes** [comment]
Feature added in tag beta-0.3
